
version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
      
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit1
    volumes:
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"

  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    volumes:
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"
    
  rabbit3:
    image: rabbitmq:3-management
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit3
    volumes:
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"

  data_access:
    container_name: data_access
    build:
      context: ./backend/
      dockerfile: ./dataAccess/Dockerfile
    depends_on:
      - rabbit1
    ports:
    - "8000:8000"

  jobmanager:
    container_name: jobmanager
    build:
      context: ./backend/
      dockerfile: ./jobmanager/Dockerfile
    depends_on:
      - rabbit1

  image_processor: 
    container_name: image_collector
    build:
      context: ./backend/
      dockerfile: ./image_processor/Dockerfile
    depends_on:
      - rabbit1

  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports: 
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:5.0.4
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  grafana-dashboards:
    image: alpine:3.10
    depends_on:
      - grafana
    volumes:
      - ./monitoring:/grafana
    command: >
      /bin/sh -c "
        apk add --no-cache curl
        echo 'waiting for grafana'
        sleep 5s
        cd /grafana
        curl --request POST http://grafana:3000/api/datasources --header 'Content-Type: application/json' -d @datasources.json
        curl --request POST http://grafana:3000/api/dashboards/db --header 'Content-Type: application/json' -d @dashboard.json"

networks:
  default:
    external:
      name: rabbitmq-cluster